from pathlib import Path
import pandas as pd
import pygmt

from .gmt_make_data import topo_vplane, tomo_grid_data
from .gmt_fig import fig_tomo


def plot_vs_vplane(grid, region, fn):
    # topo file
    topo = "ETOPO1.grd"
    topo_data = f"src/txt/{topo}"
    topo_grd = f"temp/topo_{topo}"
    topo_gra = topo_vplane(topo_grd, region)

    # gmt plot vs absolute
    # make cpt file
    cmap = "src/txt/gridvel_6_v3.cpt"
    cptfile = "temp/temp.cpt"
    pygmt.makecpt(
        cmap=cmap,
        series=[2, 4, 0.05],
        # continuous=True,
        output=cptfile,
    )
    # make vel grid and get vel grid generated by `surface`
    tomo_grd = "temp/tomo.grd"
    tomo_grid_data(grid, tomo_grd, region)
    gmt_plot_vs_vplane(region, cptfile, tomo_grd, topo_gra, f"{fn.png}")

    # # gmt plot vs related
    # # make cpt file
    # pygmt.makecpt(
    #     cmap=cmap,
    #     series=[-10, 10, 0.05],
    #     # continuous=True,
    #     output=cptfile,
    # )
    # avg = grid["v"].mean()
    # grid["v"] = 100 * (grid["v"] - avg) / avg
    # # vs_make(data, region, cptfile, tomo_grd)
    # tomo_grid_data(grid, tomo_grd, region)
    # gmt_plot_vs(region, cptfile, tomo_grd, topo_gra, f"{fn}_avg.png")


def gmt_plot_vs_vplane(region, cpt, tomo_grd, topo_gra, fname):
    fig = pygmt.Figure()

    # projection
    x = (region[0] + region[1]) / 2
    y = (region[2] + region[3]) / 2
    SCALE = f"m{x}/{y}/0.3i"
    # gmt basemap -R$olat/$elat/-250/0 -JX6i/2i -BSWne -Bxa1f1 -Bya50f50
    # position of stations
    sta = pd.read_csv(
        "src/txt/station.lst",
        usecols=[1, 2],
        index_col=None,
        header=None,
        delim_whitespace=True,
    )

    # gmt plot
    # define figure configuration
    pygmt.config(
        MAP_FRAME_TYPE="plain",
        MAP_TITLE_OFFSET="0.25p",
        MAP_DEGREE_SYMBOL="none",
        MAP_FRAME_WIDTH="0.1c",
        FONT_ANNOT_PRIMARY="20p,Times-Roman",
        FONT_TITLE="20p,Times-Roman",
        FONT="16",
    )

    # plot vel fig
    title = Path(fname).stem
    fig = fig_tomo(
        fig, tomo_grd, region, SCALE, title, cpt, topo_gra, sta
    )  # fmt: skip
    # plot colorbar
    fig.colorbar(
        cmap=cpt, position="jBC+w5c/0.4c+o0c/-1.5c+m", frame="xa0.1f0.1"
    )  # fmt: skip

    fig.savefig(fname)


def gmt_plot_vs_hplane(region, cpt, tomo_grd, topo_gra, fname):
    pass
