import pandas as pd
from pathlib import Path
import pygmt

from .gmt_make_data import topo_gradient, tomo_grid_data
from .gmt_fig import fig_htomo


def plot_misfit(grid, region, fig_name) -> None:
    # make cpt file
    # cpt file
    cptfile = "temp/temp.cpt"
    # gmt makecpt -Chot -T-0/2/0.05 -D -Z -I > tmp.cpt
    pygmt.makecpt(
        cmap="hot",
        series=[-0, 2, 0.05],
        output=cptfile,
        background=True,
        reverse=True,
        continuous=True,
    )
    # make vel grid and get vel grid generated by `surface`
    tomo_grd = "temp/tomo.grd"
    tomo_grid_data(grid, tomo_grd, region)
    # misfit_make(grid, region, cptfile, tomo_grd)

    # topo file
    topo = "ETOPO1"
    topo_data = f"src/txt/{topo}.grd"
    topo_gra = f"temp/topo_{topo}.gradient"
    topo_gradient(topo_gra, region, "t", data=topo_data)

    # gmt plot
    gmt_plot_misfit(region, cptfile, tomo_grd, topo_gra, fig_name)


def gmt_plot_misfit(region, cpt, tomo_grd, topo_gra, fname):
    fig = pygmt.Figure()

    # gmt plot
    # define figure configuration
    pygmt.config(
        MAP_FRAME_TYPE="plain",
        # MAP_TITLE_OFFSET="0.25p",
        # MAP_DEGREE_SYMBOL="none",
        # FONT_TITLE="18",
        FONT="10",
    )

    # plot vel fig
    title = Path(fname).stem
    sta = pd.read_csv(
        "src/txt/station.lst",
        usecols=[1, 2],
        index_col=None,
        header=None,
        delim_whitespace=True,
    )
    fig = fig_htomo(fig, tomo_grd, region, title, cpt, topo_gra, sta)
    # plot colorbar
    fig.colorbar(cmap=cpt, position="JRM+o0.5i/0i", frame="xa0.5f0.5")

    fig.savefig(fname)
