# set shell := ["fish", "-c"]

vi := "lvim"

# default
hello:
    @echo 'Hello, world!'
    @just --list

tree_ignore := "'grids|temp'"

# tree
tree:
  tree -I {{tree_ignore}}

pydiff := "pygmt_plot_diff.py"
pyinfo := "vel_avg_diff.py"

# edit python scripts
ep:
  {{vi}} {{pydiff}} {{pyinfo}}

# run python scripts to update the figure
up:
  python {{pydiff}}
  python {{pyinfo}}

# show figure
show:
  feh images
