# set shell := ["fish", "-c"]

vi := "lvim"

# default
hello:
    @echo 'Hello, world!'
    @just --list

tree_ignore := "'grids|temp'"

# tree
tree:
  tree -I {{tree_ignore}}

# run python scripts to update figs
up:
  python result_show.py

# show figure
show:
  feh images
